/* Studia V135 - stable selection, Word/Canva tools, cloud-ready accounts and cute assets */
(function(){
'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const icon=n=>window.v133Icon?.(n)||'';
const editor=()=>document.body.classList.contains('editorMode')&&!!q('#view-sheet-editor.active');
const desktop=()=>innerWidth>=900&&editor();
const selectedIds=()=>[...new Set([...(canvasState.selectedIds||[]),...(canvasState.selectedType==='object'&&canvasState.selectedId?[canvasState.selectedId]:[])])];
const selectedVids=()=>[...new Set([...(canvasState.selectedVectorIds||[]),...(canvasState.selectedType==='vector'&&canvasState.selectedId?[canvasState.selectedId]:[])])];
const commit=(message='')=>{renderCanvasObjects();renderVectors();renderCanvasInspector();renderLayerList();markCanvasDirty();pushHistory();requestAnimationFrame(()=>v132SyncHits?.());if(message)cuteToast?.(message)};

function syncMulti(ids,vids){canvasState.selectedIds=ids;canvasState.selectedVectorIds=vids;canvasState.selectedType=ids.length?'object':vids.length?'vector':null;canvasState.selectedId=ids.at(-1)||vids.at(-1)||null;canvasState.multiMode=false;if(ids.length+vids.length>1)window.v132ToggleMulti?.();else{renderCanvasObjects();renderVectors();renderCanvasInspector();renderLayerList();requestAnimationFrame(()=>v132SyncHits?.())}}

const baseGroup=window.groupSelectedItems;
window.groupSelectedItems=function(){const gid=baseGroup?.apply(this,arguments);if(gid){const ids=canvasState.objects.filter(x=>x.groupId===gid).map(x=>x.id),vids=canvasState.vectors.filter(x=>x.groupId===gid).map(x=>x.id);syncMulti(ids,vids)}return gid};
const baseUngroup=window.ungroupSelectedItems;
window.ungroupSelectedItems=function(){const r=baseUngroup?.apply(this,arguments);const ids=selectedIds(),vids=selectedVids();syncMulti(ids,vids);return r};
window.selectAllCanvasItems=function(){syncMulti(canvasState.objects.map(x=>x.id),canvasState.vectors.map(x=>x.id));cuteToast?.('Alles ausgewählt ♡')};
window.duplicateSelected=function(){const ids=selectedIds(),vids=selectedVids();if(!ids.length&&!vids.length)return cuteToast?.('Wähle zuerst etwas aus ♡');const newIds=[],newVids=[],groupMap=new Map();let z=typeof nextCanvasZ==='function'?nextCanvasZ():100;const remapGroup=g=>{if(!g)return null;if(!groupMap.has(g))groupMap.set(g,'grp_'+Date.now().toString(36)+'_'+groupMap.size);return groupMap.get(g)};for(const src of canvasState.objects.filter(x=>ids.includes(x.id))){const o=clone(src);o.id=id();o.x+=18;o.y+=18;o.z=z++;o.locked=false;o.editing=false;if(o.groupId)o.groupId=remapGroup(o.groupId);canvasState.objects.push(o);newIds.push(o.id)}for(const src of canvasState.vectors.filter(x=>vids.includes(x.id))){const v=clone(src);v.id=id();v.z=z++;v.locked=false;if(v.groupId)v.groupId=remapGroup(v.groupId);if(v.x!=null){v.x+=18;v.y+=18}if(v.cx!=null){v.cx+=18;v.cy+=18}if(v.points)v.points=v.points.map(p=>[p[0]+18,p[1]+18]);canvasState.vectors.push(v);newVids.push(v.id)}syncMulti(newIds,newVids);markCanvasDirty();pushHistory();cuteToast?.('Dupliziert ♡')};

window.v135Align=function(mode){const os=canvasState.objects.filter(x=>selectedIds().includes(x.id)&&!x.locked),vs=canvasState.vectors.filter(x=>selectedVids().includes(x.id)&&!x.locked);const box=v=>vectorBounds(v),items=[...os.map(ref=>({ref,kind:'o',b:{x:ref.x,y:ref.y,w:ref.w,h:ref.h}})),...vs.map(ref=>({ref,kind:'v',b:box(ref)}))];if(!items.length)return cuteToast?.('Wähle zuerst Elemente ♡');const minX=Math.min(...items.map(x=>x.b.x)),maxX=Math.max(...items.map(x=>x.b.x+x.b.w)),minY=Math.min(...items.map(x=>x.b.y)),maxY=Math.max(...items.map(x=>x.b.y+x.b.h)),cx=(minX+maxX)/2,cy=(minY+maxY)/2,W=canvasPageWidth(),H=canvasPageHeight();for(const x of items){let dx=0,dy=0;if(mode==='left')dx=(items.length>1?minX:0)-x.b.x;if(mode==='centerX')dx=(items.length>1?cx:W/2)-(x.b.x+x.b.w/2);if(mode==='right')dx=(items.length>1?maxX:W)-(x.b.x+x.b.w);if(mode==='top')dy=(items.length>1?minY:0)-x.b.y;if(mode==='centerY')dy=(items.length>1?cy:H/2)-(x.b.y+x.b.h/2);if(mode==='bottom')dy=(items.length>1?maxY:H)-(x.b.y+x.b.h);if(x.kind==='o'){x.ref.x+=dx;x.ref.y+=dy}else if(x.ref.type==='rect'){x.ref.x+=dx;x.ref.y+=dy}else if(x.ref.type==='ellipse'){x.ref.cx+=dx;x.ref.cy+=dy}else if(x.ref.points)x.ref.points=x.ref.points.map(p=>[p[0]+dx,p[1]+dy])}commit('Ausgerichtet ♡')};

window.v135ToggleStrike=function(){const o=canvasState.objects.find(x=>x.id===canvasState.selectedId);if(!o||!['text','block','task','merke'].includes(o.kind))return cuteToast?.('Wähle zuerst einen Text ♡');o.style||={};const set=new Set(String(o.style.textDecoration||'').split(/\s+/).filter(x=>x&&x!=='none'));set.has('line-through')?set.delete('line-through'):set.add('line-through');o.style.textDecoration=[...set].join(' ')||'none';commit()};
window.v135ToggleUnderline=function(){const o=canvasState.objects.find(x=>x.id===canvasState.selectedId);if(!o||!['text','block','task','merke'].includes(o.kind))return cuteToast?.('Wähle zuerst einen Text ♡');o.style||={};const set=new Set(String(o.style.textDecoration||'').split(/\s+/).filter(x=>x&&x!=='none'));set.has('underline')?set.delete('underline'):set.add('underline');o.style.textDecoration=[...set].join(' ')||'none';commit()};

window.v135ToggleMargins=function(on){canvasState.pageStyle||={};canvasState.pageStyle.showMargin=!!on;applyCanvasPageStyle();markCanvasDirty();pushHistory()};

const oldVectorEl=typeof vectorEl==='function'?vectorEl:null;
if(oldVectorEl)vectorEl=function(v){let html=oldVectorEl(v);const dash=v.dash==='solid'?'':v.dash==='dotted'?`${Math.max(1,+v.dashLength||2)} ${Math.max(1,+v.dashGap||6)}`:`${Math.max(1,+v.dashLength||10)} ${Math.max(1,+v.dashGap||7)}`;return html.replace(/stroke-dasharray="[^"]*"/g,`stroke-dasharray="${dash}"`)};
window.v135Stroke=function(prop,value){const ids=selectedIds(),vids=selectedVids();for(const o of canvasState.objects.filter(x=>ids.includes(x.id))){if(o.kind==='table'){if(prop==='dash'){o.dash=value;o.borderStyle=value==='custom'?'dashed':value}else o[prop]=value}else{o.style||={};if(prop==='dash'){o.style.dash=value;o.style.borderStyle=value==='custom'?'dashed':value}else o.style[prop]=value}}for(const v of canvasState.vectors.filter(x=>vids.includes(x.id))){if(prop==='borderColor')v.stroke=value;else if(prop==='borderWidth')v.strokeWidth=value;else v[prop]=value}commit()};

function linkSVG(){return '<svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7l-1.2 1.2M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7l1.2-1.2"/></svg>'}
window.openHyperlinkDialog=function(editId=''){const old=canvasState.objects.find(x=>x.id===(editId||canvasState.selectedId)),sheets=(data.studySheets||[]).filter(x=>x.id!==selectedSheetId);openModal(`<div class="v135Modal"><div class="v135ModalHead"><div><span class="eyebrow">VERLINKEN</span><h2>Hyperlink einfügen</h2></div><button onclick="closeModal()">×</button></div><p>Verlinke eine Webseite oder springe direkt zu einem deiner Lernblätter.</p><div class="v135FormGrid"><label class="full">Anzeigetext<input id="v135LinkText" value="${esc(old?.text?.replace(/<[^>]*>/g,'')||'Lernlink')}"></label><label>Web-Adresse<input id="v135LinkUrl" type="url" placeholder="https://…" value="${esc(old?.linkUrl||'')}"></label><label>Lernblatt<select id="v135LinkSheet"><option value="">Keines</option>${sheets.map(x=>`<option value="${x.id}" ${old?.linkSheetId===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label></div><div class="v135ActionRow"><button onclick="closeModal()">Abbrechen</button><button class="primary" onclick="v135SaveLink('${old?.id||''}')">Link speichern</button></div></div>`)};
window.v135SaveLink=function(editId=''){let o=canvasState.objects.find(x=>x.id===editId);if(!o||!['text','block','task','merke'].includes(o.kind)){o=newCanvasObject('body');o.x=110;o.y=150;o.w=330;o.h=54;canvasState.objects.push(o)}o.text=esc(q('#v135LinkText')?.value||'Lernlink');o.linkUrl=String(q('#v135LinkUrl')?.value||'').trim();o.linkSheetId=q('#v135LinkSheet')?.value||'';o.style||={};o.style.color='#8f5f91';o.style.textDecoration='underline';closeModal();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];commit('Link eingefügt ♡')};
window.v135OpenLink=function(idv){const o=canvasState.objects.find(x=>x.id===idv);if(!o)return;if(o.linkSheetId){saveCanvasSheet?.();openStudySheetEditor(o.linkSheetId);return}if(o.linkUrl){let url=o.linkUrl;if(!/^https?:\/\//i.test(url))url='https://'+url;window.open(url,'_blank','noopener')}};

function palette(n=6){const p=['#f09aa5','#efc4a6','#bad6a2','#9ccfd2','#b7a6d9','#f1d783','#d6a6bd','#8fb5dc'];return Array.from({length:n},(_,i)=>p[i%p.length])}
window.openChartDialog=function(editId=''){const o=canvasState.objects.find(x=>x.id===editId),c=o?.chart||{};openModal(`<div class="v135Modal"><div class="v135ModalHead"><div><span class="eyebrow">DIAGRAMME</span><h2>${o?'Diagramm bearbeiten':'Diagramm erstellen'}</h2></div><button onclick="closeModal()">×</button></div><div class="v135FormGrid"><label>Art<select id="v135ChartType"><option value="bar">Säulen</option><option value="hbar" ${c.type==='hbar'?'selected':''}>Balken</option><option value="line" ${c.type==='line'?'selected':''}>Linie</option><option value="area" ${c.type==='area'?'selected':''}>Fläche</option><option value="pie" ${c.type==='pie'?'selected':''}>Kreis</option><option value="donut" ${c.type==='donut'?'selected':''}>Ring</option></select></label><label>Titel<input id="v135ChartTitle" value="${esc(c.title||'Mein Diagramm')}"></label><label class="full">Beschriftungen, mit Komma getrennt<input id="v135ChartLabels" value="${esc((c.labels||['A','B','C','D']).join(', '))}"></label><label class="full">Werte, mit Komma getrennt<input id="v135ChartValues" value="${esc((c.values||[8,14,11,17]).join(', '))}"></label><label class="full">Farben<input id="v135ChartColors" value="${esc((c.colors||palette(4)).join(', '))}"></label></div><div class="v135ActionRow"><button onclick="closeModal()">Abbrechen</button><button class="primary" onclick="v135SaveChart('${o?.id||''}')">Diagramm einfügen</button></div></div>`)};
window.v135SaveChart=function(editId=''){const labels=String(q('#v135ChartLabels')?.value||'A,B,C').split(',').map(x=>x.trim()).filter(Boolean),values=String(q('#v135ChartValues')?.value||'1,2,3').split(',').map(Number).map(x=>Number.isFinite(x)?x:0),colors=String(q('#v135ChartColors')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);while(values.length<labels.length)values.push(0);let o=canvasState.objects.find(x=>x.id===editId);if(!o){o={id:id(),z:nextCanvasZ(),kind:'chart',x:120,y:180,w:500,h:320,rotation:0,locked:false};canvasState.objects.push(o)}o.chart={type:q('#v135ChartType')?.value||'bar',title:q('#v135ChartTitle')?.value||'',labels,values:values.slice(0,labels.length),colors:colors.length?colors:palette(labels.length)};closeModal();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];commit('Diagramm eingefügt ♡')};

function chartSVG(c,w,h){const labels=c.labels||[],vals=c.values||[],colors=c.colors?.length?c.colors:palette(labels.length),max=Math.max(1,...vals.map(Math.abs)),left=42,top=42,right=16,bottom=38,pw=w-left-right,ph=h-top-bottom;let s=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" rx="14" fill="#fffdfb"/><text x="16" y="25" class="v135ChartTitle">${esc(c.title||'Diagramm')}</text>`;if(['pie','donut'].includes(c.type)){const total=Math.max(1,vals.reduce((a,b)=>a+Math.max(0,b),0)),cx=w*.39,cy=h*.54,r=Math.min(w,h)*.25;let a=-Math.PI/2;vals.forEach((v,i)=>{const d=Math.max(0,v)/total*Math.PI*2,x1=cx+Math.cos(a)*r,y1=cy+Math.sin(a)*r;a+=d;const x2=cx+Math.cos(a)*r,y2=cy+Math.sin(a)*r,large=d>Math.PI?1:0;s+=`<path d="M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2} Z" fill="${esc(colors[i%colors.length])}"/>`});if(c.type==='donut')s+=`<circle cx="${cx}" cy="${cy}" r="${r*.52}" fill="#fffdfb"/>`;labels.forEach((x,i)=>s+=`<circle cx="${w*.72}" cy="${60+i*22}" r="5" fill="${esc(colors[i%colors.length])}"/><text x="${w*.72+11}" y="${64+i*22}" font-size="10" fill="#665b55">${esc(x)} · ${vals[i]??0}</text>`);return s+'</svg>'}s+=`<path d="M${left} ${top}V${top+ph}H${left+pw}" fill="none" stroke="#d9cfca"/>`;if(c.type==='hbar'){const bh=ph/Math.max(1,labels.length);labels.forEach((x,i)=>{const ww=Math.abs(vals[i]||0)/max*pw;s+=`<rect x="${left}" y="${top+i*bh+bh*.18}" width="${ww}" height="${bh*.58}" rx="5" fill="${esc(colors[i%colors.length])}"/><text x="${left-6}" y="${top+i*bh+bh*.56}" text-anchor="end" font-size="9" fill="#756861">${esc(x)}</text>`})}else if(['line','area'].includes(c.type)){const pts=vals.map((v,i)=>[left+(i/(Math.max(1,vals.length-1)))*pw,top+ph-(Math.abs(v)/max)*ph]);const d=pts.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ');if(c.type==='area'&&pts.length)s+=`<path d="${d} L ${pts.at(-1)[0]} ${top+ph} L ${pts[0][0]} ${top+ph} Z" fill="${esc(colors[0])}" opacity=".24"/>`;s+=`<path d="${d}" fill="none" stroke="${esc(colors[0])}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`;pts.forEach((p,i)=>s+=`<circle cx="${p[0]}" cy="${p[1]}" r="4" fill="${esc(colors[i%colors.length])}"/><text x="${p[0]}" y="${top+ph+17}" text-anchor="middle" font-size="9" fill="#756861">${esc(labels[i]||'')}</text>`)}else{const bw=pw/Math.max(1,labels.length);labels.forEach((x,i)=>{const hh=Math.abs(vals[i]||0)/max*ph;s+=`<rect x="${left+i*bw+bw*.18}" y="${top+ph-hh}" width="${bw*.64}" height="${hh}" rx="6" fill="${esc(colors[i%colors.length])}"/><text x="${left+i*bw+bw*.5}" y="${top+ph+17}" text-anchor="middle" font-size="9" fill="#756861">${esc(x)}</text>`})}return s+'</svg>'}

window.openTimelineDialog=function(editId=''){const o=canvasState.objects.find(x=>x.id===editId),t=o?.timeline||{};openModal(`<div class="v135Modal"><div class="v135ModalHead"><div><span class="eyebrow">ZEITLEISTE</span><h2>${o?'Timeline bearbeiten':'Timeline einfügen'}</h2></div><button onclick="closeModal()">×</button></div><div class="v135FormGrid"><label>Titel<input id="v135TimeTitle" value="${esc(t.title||'Meine Timeline')}"></label><label>Anzahl Zeitpunkte<input id="v135TimeCount" type="number" min="2" max="12" value="${t.count||4}"></label><label class="full">Beschriftungen, mit Komma getrennt<input id="v135TimeLabels" value="${esc((t.labels||['Start','Schritt 2','Schritt 3','Ziel']).join(', '))}"></label><label>Linienfarbe<input id="v135TimeColor" type="color" value="${t.color||'#e7919b'}"></label><label>Punktfarbe<input id="v135TimeAccent" type="color" value="${t.accent||'#f6c4c9'}"></label></div><div class="v135ActionRow"><button onclick="closeModal()">Abbrechen</button><button class="primary" onclick="v135SaveTimeline('${o?.id||''}')">Timeline einfügen</button></div></div>`)};
window.v135SaveTimeline=function(editId=''){const count=Math.max(2,Math.min(12,+q('#v135TimeCount')?.value||4)),raw=String(q('#v135TimeLabels')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);while(raw.length<count)raw.push('Schritt '+(raw.length+1));let o=canvasState.objects.find(x=>x.id===editId);if(!o){o={id:id(),z:nextCanvasZ(),kind:'timeline',x:105,y:210,w:580,h:190,rotation:0,locked:false};canvasState.objects.push(o)}o.timeline={title:q('#v135TimeTitle')?.value||'',count,labels:raw.slice(0,count),color:q('#v135TimeColor')?.value||'#e7919b',accent:q('#v135TimeAccent')?.value||'#f6c4c9'};closeModal();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];commit('Timeline eingefügt ♡')};
function timelineSVG(t,w,h){const count=t.count||t.labels?.length||4,pad=42,y=h*.52,step=(w-pad*2)/Math.max(1,count-1);let s=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" rx="14" fill="#fffdfb"/><text x="18" y="27" class="v135TimelineTitle">${esc(t.title||'Timeline')}</text><path d="M${pad} ${y}H${w-pad}" stroke="${esc(t.color||'#e7919b')}" stroke-width="4" stroke-linecap="round"/>`;for(let i=0;i<count;i++){const x=pad+i*step,up=i%2===0;s+=`<circle cx="${x}" cy="${y}" r="10" fill="${esc(t.accent||'#f6c4c9')}" stroke="${esc(t.color||'#e7919b')}" stroke-width="3"/><path d="M${x} ${y+(up?-10:10)}V${y+(up?-28:28)}" stroke="${esc(t.color||'#e7919b')}"/><text x="${x}" y="${y+(up?-36:45)}" text-anchor="middle" font-size="10" font-weight="700" fill="#655852">${esc(t.labels?.[i]||'')}</text>`}return s+'</svg>'}

const stickerAssets=['title-1.png','title-2.png','title-3.png','title-4.png','pins-1.png','pins-2.png','notes-1.png','notes-2.png','notes-3.png','notes-4.png','notes-5.png','notes-6.png','notes-7.png'];
const paperclip='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 200"><path d="M95 31c25 2 39 24 33 48l-25 91c-5 19-24 30-42 25-18-5-29-24-24-42l26-96c3-12 15-19 27-16s19 15 16 27l-24 87c-1 5-6 8-11 6-5-1-8-6-6-11l22-81" fill="none" stroke="#e78596" stroke-width="12" stroke-linecap="round"/></svg>');
window.openStickerLibrary=function(){openModal(`<div class="v135Modal"><div class="v135ModalHead"><div><span class="eyebrow">STICKER</span><h2>Süße Sticker</h2></div><button onclick="closeModal()">×</button></div><p>Deine Illustrator-Sticker plus Büroklammer und weitere Deko.</p><div class="v135StickerGrid"><button title="Büroklammer" onclick="v135AddStickerAsset('${paperclip}','Büroklammer')"><img src="${paperclip}"></button>${stickerAssets.map((f,i)=>`<button title="Sticker ${i+1}" onclick="v135AddStickerAsset('assets/stickers/${f}','Sticker ${i+1}')"><img src="assets/stickers/${f}"></button>`).join('')}</div></div>`)};
window.v135AddStickerAsset=function(src,label){const o={id:id(),z:nextCanvasZ(),kind:'image',src,name:label,x:150,y:150,w:src.includes('pins')?130:src.includes('title')?320:240,h:src.includes('pins')?170:src.includes('title')?135:210,rotation:0,locked:false,stickerAsset:true};canvasState.objects.push(o);closeModal();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];commit('Sticker eingefügt ♡')};

function renderSpecial(){for(const o of canvasState.objects||[]){const el=q(`.cobj[data-id="${CSS.escape(o.id)}"]`);if(!el)continue;if(o.kind==='chart'&&o.chart){const sig='chart:'+JSON.stringify(o.chart)+':'+o.w+':'+o.h;if(el.dataset.v135Special!==sig){el.contentEditable='false';el.innerHTML=`<div class="v135Special">${chartSVG(o.chart,Math.max(220,o.w),Math.max(160,o.h))}</div><span class="rotateHandle"></span><span class="resizeHandle"></span>`;el.dataset.v135Special=sig}}else if(o.kind==='timeline'&&o.timeline){const sig='timeline:'+JSON.stringify(o.timeline)+':'+o.w+':'+o.h;if(el.dataset.v135Special!==sig){el.contentEditable='false';el.innerHTML=`<div class="v135Special">${timelineSVG(o.timeline,Math.max(280,o.w),Math.max(120,o.h))}</div><span class="rotateHandle"></span><span class="resizeHandle"></span>`;el.dataset.v135Special=sig}}if(o.kind==='paper')el.style.setProperty('--v135-paper-line',o.patternColor||'#9aafc1');if(o.linkUrl||o.linkSheetId){el.classList.add('v135Linked');if(!el.querySelector('.v135LinkBadge'))el.insertAdjacentHTML('beforeend',`<button class="v135LinkBadge" title="Link öffnen" onclick="event.stopPropagation();v135OpenLink('${o.id}')">${linkSVG()}</button>`)}const st=o.kind==='table'?o:(o.style||{}),dash=o.kind==='table'?(o.dash||o.borderStyle):(st.dash||st.borderStyle),bw=Math.max(0,+(o.kind==='table'?o.borderWidth:st.borderWidth)||0);if(bw&&dash&&dash!=='solid'&&!el.querySelector('.v135StrokeOverlay')){const color=o.kind==='table'?(o.borderColor||'#8d7369'):(st.borderColor||'#8d7369'),len=Math.max(1,+(o.kind==='table'?o.dashLength:st.dashLength)||(dash==='dotted'?2:10)),gap=Math.max(1,+(o.kind==='table'?o.dashGap:st.dashGap)||(dash==='dotted'?6:7)),rad=Math.max(0,+(o.kind==='table'?o.borderRadius:st.borderRadius)||0);el.insertAdjacentHTML('beforeend',`<svg class="v135StrokeOverlay" viewBox="0 0 ${Math.max(1,o.w)} ${Math.max(1,o.h)}" preserveAspectRatio="none"><rect x="${bw/2}" y="${bw/2}" width="${Math.max(1,o.w-bw)}" height="${Math.max(1,o.h-bw)}" rx="${rad}" fill="none" stroke="${esc(color)}" stroke-width="${bw}" stroke-dasharray="${len} ${gap}"/></svg>`);if(o.kind!=='table')el.style.borderColor='transparent'}}}
const baseRenderObjects=window.renderCanvasObjects;window.renderCanvasObjects=function(){const r=baseRenderObjects.apply(this,arguments);renderSpecial();requestAnimationFrame(()=>v132SyncHits?.());return r};try{renderCanvasObjects=window.renderCanvasObjects}catch(_){}

function outlineInspector(){const host=q('#canvasInspector');if(!host||!canvasState.selectedId)return;const ids=selectedIds(),vids=selectedVids(),o=canvasState.objects.find(x=>x.id===canvasState.selectedId),v=canvasState.vectors.find(x=>x.id===canvasState.selectedId),ref=v||o,style=v?v:(o?.kind==='table'?o:o?.style||{}),dash=v?.dash||(o?.kind==='table'?(o?.dash||o?.borderStyle):(style.dash||style.borderStyle))||'solid',dl=v?.dashLength||style.dashLength||10,dg=v?.dashGap||style.dashGap||7;const box=document.createElement('div');box.className='v135InspectorBlock';box.innerHTML=`<div class="v135InspectorTitle">Kontur & Anordnen <span>${ids.length+vids.length>1?'Mehrfachauswahl':'Auswahl'}</span></div><div class="v135InspectorGrid"><label>Linienart<select onchange="v135Stroke('dash',this.value)"><option value="solid" ${dash==='solid'?'selected':''}>Durchgezogen</option><option value="dashed" ${dash==='dashed'?'selected':''}>Gestrichelt</option><option value="dotted" ${dash==='dotted'?'selected':''}>Gepunktet</option><option value="custom" ${dash==='custom'?'selected':''}>Eigene Striche</option></select></label><label>Konturfarbe<input type="color" value="${v?.stroke||o?.borderColor||style.borderColor||'#8d7369'}" onchange="v135Stroke('borderColor',this.value)"></label><label>Strichlänge<input type="number" min="1" max="80" value="${dl}" onchange="v135Stroke('dashLength',+this.value)"></label><label>Abstand<input type="number" min="1" max="80" value="${dg}" onchange="v135Stroke('dashGap',+this.value)"></label></div><div class="v135AlignGrid"><button onclick="v135Align('left')">Links</button><button onclick="v135Align('centerX')">Mittig</button><button onclick="v135Align('right')">Rechts</button><button onclick="v135Align('top')">Oben</button><button onclick="v135Align('centerY')">Mitte</button><button onclick="v135Align('bottom')">Unten</button></div>`;host.prepend(box);if(o?.kind==='paper'){const p=document.createElement('div');p.className='v135InspectorBlock';p.innerHTML=`<div class="v135InspectorTitle">Papier gestalten <span>${o.paperType==='grid'?'Kariert':'Liniert'}</span></div><div class="v135InspectorGrid"><label>Papierfarbe<input type="color" value="${o.paperColor||'#fffdf7'}" onchange="v135Paper('paperColor',this.value)"></label><label>Linienfarbe<input type="color" value="${o.patternColor||'#9aafc1'}" onchange="v135Paper('patternColor',this.value)"></label></div>`;host.prepend(p)}if(o?.kind==='chart'){const b=document.createElement('button');b.className='primary';b.textContent='Diagramm bearbeiten';b.onclick=()=>openChartDialog(o.id);host.prepend(b)}if(o?.kind==='timeline'){const b=document.createElement('button');b.className='primary';b.textContent='Timeline bearbeiten';b.onclick=()=>openTimelineDialog(o.id);host.prepend(b)}}
window.v135Paper=function(prop,value){const o=canvasState.objects.find(x=>x.id===canvasState.selectedId);if(!o||o.kind!=='paper')return;o[prop]=value;commit()};
const baseInspector=window.renderCanvasInspector;window.renderCanvasInspector=function(){const r=baseInspector.apply(this,arguments);outlineInspector();return r};try{renderCanvasInspector=window.renderCanvasInspector}catch(_){}

function ensureLayers(){canvasState.layerGroups||=[];if(!canvasState.layerGroups.length)canvasState.layerGroups.push({id:'layer-main',name:'Ebene 1'});const first=canvasState.layerGroups[0].id;[...(canvasState.objects||[]),...(canvasState.vectors||[])].forEach(x=>x.layerGroupId||=first)}
function layerRef(kind,idv){return kind==='object'?canvasState.objects.find(x=>x.id===idv):canvasState.vectors.find(x=>x.id===idv)}
function layerName(ref,kind){if(kind==='vector')return ref.shapeKind==='star'?'Stern':ref.type==='ellipse'?'Kreis':ref.type==='triangle'?'Dreieck':ref.type==='path'?'Pfad':'Form';return ref.name||({text:'Text',block:'Textblock',table:'Tabelle',image:'Bild / Sticker',formula:'Formel',graph:'Graph',chart:'Diagramm',timeline:'Timeline',paper:'Papier',tape:'Klebeband'}[ref.kind]||'Element')}
function layerIcon(ref,kind){if(kind==='vector')return icon(ref.type==='ellipse'?'circle':ref.type==='triangle'?'triangle':ref.shapeKind==='star'?'star':ref.type==='path'?'curve':'rect');return icon(({text:'text',block:'text',table:'table',image:'image',formula:'formula',graph:'graph',chart:'graph',timeline:'line',paper:'paperline',tape:'tape'}[ref.kind]||'elements'))}
function layerMarkup(){ensureLayers();const entries=layerEntries();return `<div class="v135LayerWrap"><div class="v135LayersToolbar"><b>Ebenen</b><button onclick="v135AddLayerGroup()">＋ Neue Ebene</button></div>${canvasState.layerGroups.map((g,gi)=>{const rows=entries.filter(a=>layerRef(a.kind,a.id)?.layerGroupId===g.id);return `<section class="v135LayerGroup" style="animation-delay:${gi*35}ms"><div class="v135LayerGroupHead"><div><b>${esc(g.name)}</b> <span>${rows.length} Elemente</span></div><button title="Umbenennen" onclick="v135RenameLayerGroup('${g.id}')">✎</button><button title="Löschen" onclick="v135DeleteLayerGroup('${g.id}')">×</button></div><div class="v135LayerItems">${rows.length?rows.map(a=>{const ref=layerRef(a.kind,a.id);return `<div class="v130LayerRow v135LayerRow ${canvasState.selectedId===a.id?'active':''}" data-layer-kind="${a.kind}" data-layer-id="${a.id}"><button class="v130LayerHandle" onpointerdown="v130LayerPointerStart(event,'${a.kind}','${a.id}')">${icon('drag')}</button><button class="v130LayerTitle" onclick="${a.kind==='object'?`selectCanvasObject('${a.id}')`:`selectVector('${a.id}')`}"><span class="v135LayerIcon">${layerIcon(ref,a.kind)}</span><span class="v131LayerText">${esc(layerName(ref,a.kind))}</span></button><select title="Ebene wählen" onchange="v135AssignLayer('${a.kind}','${a.id}',this.value)">${canvasState.layerGroups.map(x=>`<option value="${x.id}" ${x.id===g.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button class="v135LayerLock" title="${ref.locked?'Entsperren':'Sperren'}" onclick="event.stopPropagation();${a.kind==='object'?`selectCanvasObject('${a.id}')`:`selectVector('${a.id}')`};toggleSelectedLock()">${icon(ref.locked?'unlock':'lock')}</button></div>`}).join(''):'<div class="v135LayerEmpty">Elemente hier einsortieren</div>'}</div></section>`}).join('')}</div>`}
window.renderLayerList=function(){const html=layerMarkup(),a=q('#layerList');if(a)a.innerHTML=html;const b=q('#canvasQuickDrawer.open .mobileLayerList');if(b)b.innerHTML=html};try{renderLayerList=window.renderLayerList}catch(_){}
window.v135AddLayerGroup=function(){ensureLayers();canvasState.layerGroups.push({id:'layer-'+Date.now().toString(36),name:'Ebene '+(canvasState.layerGroups.length+1)});renderLayerList();markCanvasDirty();pushHistory()};
window.v135RenameLayerGroup=function(gid){const g=canvasState.layerGroups.find(x=>x.id===gid),n=prompt('Name der Ebene',g?.name||'Ebene');if(!g||!n?.trim())return;g.name=n.trim();renderLayerList();markCanvasDirty();pushHistory()};
window.v135DeleteLayerGroup=function(gid){ensureLayers();if(canvasState.layerGroups.length<2)return cuteToast?.('Mindestens eine Ebene bleibt erhalten ♡');const fallback=canvasState.layerGroups.find(x=>x.id!==gid)?.id;[...canvasState.objects,...canvasState.vectors].forEach(x=>{if(x.layerGroupId===gid)x.layerGroupId=fallback});canvasState.layerGroups=canvasState.layerGroups.filter(x=>x.id!==gid);renderLayerList();markCanvasDirty();pushHistory()};
window.v135AssignLayer=function(kind,idv,gid){const ref=layerRef(kind,idv);if(!ref)return;ref.layerGroupId=gid;renderLayerList();markCanvasDirty();pushHistory()};

function pageExtras(){const ps=canvasState.pageStyle||{},targets=[q('.v102SidePageSettings'),q('#canvasQuickDrawer.open .mobilePagePanel')].filter(Boolean);for(const t of targets){if(t.querySelector('.v135PageExtras'))continue;const d=document.createElement('div');d.className='v135PageExtras v135InspectorBlock';d.innerHTML=`<div class="v135InspectorTitle">Papier & Seitenrand <span>nicht im Druck</span></div><div class="v135InspectorGrid"><label>Musterfarbe<input type="color" value="${ps.patternColor||'#8197ae'}" onchange="setCanvasPageStyle('patternColor',this.value)"></label><label>Rand anzeigen<input type="checkbox" ${ps.showMargin!==false?'checked':''} onchange="v135ToggleMargins(this.checked)"></label></div><div class="v135Hint">Objekte rasten beim Ziehen automatisch am sichtbaren Seitenrand ein. Der Rand wird nie mitgedruckt.</div>`;t.appendChild(d)}}

function addToolbarTools(){const tools=q('.v134FormatTools');if(tools&&!tools.querySelector('.v135Justify')){const sep=tools.querySelectorAll('.sep')[1]||tools.querySelector('.sep');const html=`<button class="v135TextButton v135Justify" title="Blocksatz" onclick="applyTextProperty('textAlign','justify')">☰</button><button class="v135TextButton" title="Durchstreichen" onclick="v135ToggleStrike()"><s>S</s></button><button class="v135TextButton" title="Hyperlink" onclick="openHyperlinkDialog()">${linkSVG()}</button><button class="v135TextButton" title="Eigene Schrift hinzufügen" onclick="v91PickFont()">${icon('plus')}</button>`;sep?.insertAdjacentHTML('beforebegin',html)}const command=q('.desktopCommandBar');if(command&&!command.querySelector('.v135SideOpen'))command.insertAdjacentHTML('beforeend',`<button class="v135SideOpen" title="Rechte Leiste anzeigen" onclick="v135ToggleSidebar(true)">${icon('pages')}</button>`)}
function addMenus(){const top=q('.canvasTopbar');if(!top||top.querySelector('.v135MenuBar'))return;const bar=document.createElement('nav');bar.className='v135MenuBar';bar.innerHTML=['Datei','Bearbeiten','Ansicht','Einfügen','Format','Anordnen','Extras','Hilfe'].map(x=>`<button onclick="v135Menu('${x}')">${x}</button>`).join('');top.appendChild(bar)}
window.v135Menu=function(name){if(name==='Datei')return saveCanvasSheet?.();if(name==='Bearbeiten'||name==='Hilfe')return openShortcutHelp?.();if(name==='Ansicht')return v135ToggleSidebar();if(name==='Einfügen')return openChartDialog();if(name==='Format')return v91PickFont?.();if(name==='Anordnen')return renderCanvasInspector();if(name==='Extras')return openAccountDialog()};
window.v135ToggleSidebar=function(force){const closed=document.body.classList.contains('v135SideClosed'),next=force===true?false:!closed;document.body.classList.toggle('v135SideClosed',next);localStorage.setItem('studia-v135-side',next?'closed':'open')};
function sideClose(){const side=q('#desktopEditorSidebar');if(side&&!side.querySelector('.v135SideClose'))side.insertAdjacentHTML('afterbegin','<button class="v135SideClose" title="Leiste schließen" onclick="v135ToggleSidebar()">×</button>')}

function enhancePalette(){const d=q('#canvasQuickDrawer');if(!d)return;const mode=d.dataset.v134Mode;if((mode==='charts'||mode==='elements')&&!d.querySelector('[data-v135="chart"]')){const grid=q('.v134PaletteGrid',d);if(grid)grid.insertAdjacentHTML('beforeend',`<button class="v134PaletteTile" data-v135="chart" onclick="openChartDialog()">${icon('graph')}<span>Diagramm</span></button><button class="v134PaletteTile" onclick="openTimelineDialog()">${icon('line')}<span>Timeline</span></button><button class="v134PaletteTile" onclick="openHyperlinkDialog()">${linkSVG()}<span>Hyperlink</span></button>`)}if(mode==='stickers'&&!d.querySelector('[data-v135="stickers"]')){q('.v134PaletteGrid',d)?.insertAdjacentHTML('afterbegin',`<button class="v134PaletteTile" data-v135="stickers" onclick="openStickerLibrary()">${icon('sticker')}<span>Süße Sticker</span></button>`)}}

const FIREBASE_VERSION='12.18.0';let fb=null,cloudTimer=null;
async function loadFirebase(){if(fb)return fb;const base=`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/`;const [app,auth,fs]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js')]);const cfg=JSON.parse(localStorage.getItem('studia-firebase-config')||'null');if(!cfg?.apiKey||!cfg?.projectId)throw new Error('Firebase-Konfiguration fehlt.');const a=app.getApps().length?app.getApps()[0]:app.initializeApp(cfg);fb={app:a,auth:auth.getAuth(a),db:fs.getFirestore(a),authApi:auth,fsApi:fs};return fb}
window.openAccountDialog=function(){const cfg=localStorage.getItem('studia-firebase-config')||'';openModal(`<div class="v135Modal"><div class="v135ModalHead"><div><span class="eyebrow">KOSTENLOSES KONTO</span><h2>Studia Cloud</h2></div><button onclick="closeModal()">×</button></div><p>Mit Firebase Email/Passwort kannst du dieselben Daten auf Handy und Laptop laden. Die Projekt-Konfiguration wird nur auf diesem Gerät gespeichert.</p><div class="v135FormGrid"><label class="full">Firebase Web-Konfiguration (JSON)<textarea id="v135FirebaseConfig" placeholder='{"apiKey":"…","authDomain":"…","projectId":"…","appId":"…"}'>${esc(cfg)}</textarea></label><label>E-Mail<input id="v135CloudEmail" type="email" autocomplete="email"></label><label>Passwort<input id="v135CloudPassword" type="password" autocomplete="current-password" minlength="6"></label></div><div class="v135CloudState" id="v135CloudState"></div><div class="v135ActionRow"><button onclick="v135CloudAuth('register')">Konto erstellen</button><button onclick="v135CloudAuth('login')">Anmelden</button><button onclick="v135CloudDownload()">Cloud laden</button><button class="primary" onclick="v135CloudUpload()">Jetzt synchronisieren</button></div><div class="v135Hint">Einmalig nötig: kostenloses Firebase-Projekt anlegen, Email/Passwort-Anmeldung und Firestore aktivieren. Zugangsdaten erfindet Studia nicht; du fügst die Web-Konfiguration deines Projekts hier ein.</div></div>`)};
function cloudState(s){const el=q('#v135CloudState');if(el)el.textContent=s}
window.v135CloudAuth=async function(mode){try{const raw=q('#v135FirebaseConfig')?.value.trim();if(raw){JSON.parse(raw);localStorage.setItem('studia-firebase-config',raw);fb=null}cloudState('Verbindung wird hergestellt …');const x=await loadFirebase(),email=q('#v135CloudEmail')?.value.trim(),pw=q('#v135CloudPassword')?.value||'';const cred=mode==='register'?await x.authApi.createUserWithEmailAndPassword(x.auth,email,pw):await x.authApi.signInWithEmailAndPassword(x.auth,email,pw);cloudState('Angemeldet als '+cred.user.email);localStorage.setItem('studia-cloud-user',cred.user.uid);enableCloudAuto();cuteToast?.('Cloud-Konto verbunden ♡')}catch(err){cloudState('Fehler: '+String(err.message||err).replace(/^Firebase:\s*/i,''))}};
window.v135CloudUpload=async function(silent=false){try{const x=await loadFirebase(),u=x.auth.currentUser;if(!u)throw new Error('Bitte zuerst anmelden.');const payload=JSON.stringify(data);await x.fsApi.setDoc(x.fsApi.doc(x.db,'users',u.uid,'studia','main'),{payload,updatedAt:x.fsApi.serverTimestamp()},{merge:true});localStorage.setItem('studia-cloud-last',String(Date.now()));if(!silent)cloudState('Alles synchronisiert ✓')}catch(err){if(!silent)cloudState('Fehler: '+(err.message||err))}};
window.v135CloudDownload=async function(){try{const x=await loadFirebase(),u=x.auth.currentUser;if(!u)throw new Error('Bitte zuerst anmelden.');cloudState('Cloud-Daten werden geladen …');const snap=await x.fsApi.getDoc(x.fsApi.doc(x.db,'users',u.uid,'studia','main'));if(!snap.exists())throw new Error('Noch keine Cloud-Daten vorhanden.');const remote=JSON.parse(snap.data().payload||'{}');Object.keys(data).forEach(k=>delete data[k]);Object.assign(data,remote);save();cloudState('Cloud-Daten geladen ✓');setTimeout(()=>location.reload(),500)}catch(err){cloudState('Fehler: '+(err.message||err))}};
function enableCloudAuto(){if(cloudTimer)return;cloudTimer=setInterval(()=>v135CloudUpload(true),45000)}

function mobileExtras(){const d=q('#canvasQuickDrawer.open');if(!d||d.querySelector('.v135MobileExtras'))return;const section=q('.mobileDrawerSection,.mobileTextLibrary,.mobilePagePanel',d);if(!section)return;const x=document.createElement('div');x.className='v135MobileExtras';x.innerHTML=`<button onclick="openHyperlinkDialog()">${linkSVG()} Hyperlink</button><button onclick="openChartDialog()">${icon('graph')} Diagramm</button><button onclick="openTimelineDialog()">${icon('line')} Timeline</button><button onclick="openStickerLibrary()">${icon('sticker')} Sticker</button><button onclick="applyTextProperty('textAlign','justify')">☰ Blocksatz</button><button onclick="v135ToggleStrike()"><s>S</s> Durchstreichen</button><button onclick="openAccountDialog()">${icon('lock')} Cloud-Konto</button>`;section.appendChild(x)}

function reconcile(){if(!editor())return;ensureLayers();renderSpecial();if(desktop()){addMenus();addToolbarTools();sideClose();document.body.classList.toggle('v135SideClosed',localStorage.getItem('studia-v135-side')==='closed')}pageExtras();enhancePalette();mobileExtras();requestAnimationFrame(()=>v132SyncHits?.())}
const oldV134Open=window.v134Open;if(oldV134Open)window.v134Open=function(){const r=oldV134Open.apply(this,arguments);setTimeout(()=>{enhancePalette();pageExtras()},30);return r};
const oldV132Open=window.v132Open;if(oldV132Open)window.v132Open=function(){const r=oldV132Open.apply(this,arguments);setTimeout(()=>{mobileExtras();pageExtras();if(arguments[0]==='layers')renderLayerList()},40);return r};
const oldApplyStyle=window.setCanvasPageStyle;window.setCanvasPageStyle=function(prop,value){const r=oldApplyStyle.apply(this,arguments);setTimeout(pageExtras,10);return r};
document.addEventListener('keydown',e=>{if(!editor())return;const typing=e.target?.matches?.('input,textarea,select')||e.target?.isContentEditable,mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='k'&&!typing){e.preventDefault();e.stopImmediatePropagation();openHyperlinkDialog()}},{capture:true});
const obs=new MutationObserver(()=>requestAnimationFrame(reconcile));obs.observe(document.body,{subtree:true,childList:true});
window.addEventListener('resize',()=>setTimeout(reconcile,160));setTimeout(reconcile,1100);
})();
