/* Studia V140 — durable tools, frame sticker and Apps Script sync */
(function(){
'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const editor=()=>document.body.classList.contains('editorMode')&&!!q('#view-sheet-editor.active');
const icon=d=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`;
const uploadIcon=icon('M12 16V4m0 0L7 9m5-5 5 5M5 14v5h14v-5');
const frameIcon='<svg viewBox="0 0 80 34" aria-hidden="true"><path d="M77 6v22c-4 0-7 3-7 5H10c0-2-3-5-7-5V6c4 0 7-3 7-5h60c0 2 3 5 7 5Z"/></svg>';
let wantedMode='elements',navGuard=0,elementMarkup='';

function rememberMode(){const a=q('.canvasQuickNav button.active');wantedMode=a?.dataset.v139||a?.dataset.v138||wantedMode}
function forceNav(){if(!editor())return;window.dispatchEvent(new Event('v140-stabilize'));if(typeof window.v138NavOpen!=='function')return;const nav=q('.canvasQuickNav');if(!nav)return;const labels=qa('button',nav).map(x=>x.textContent.trim()).join('|');if(labels!=='Text|Elemente|Vorlagen|Seiten|Ebenen'||qa('button svg',nav).length<5){q('.v139NavSentinel',nav)?.remove();nav.innerHTML='';if(typeof window.v139ForceNav==='function')window.v139ForceNav(wantedMode);else return}qa('button',nav).forEach(b=>{const mode=b.dataset.v139||b.dataset.v138;if(!mode)return;b.classList.toggle('active',mode===wantedMode);b.onclick=()=>{wantedMode=mode;window.v138NavOpen(mode,b);setTimeout(enhanceDrawer,0);setTimeout(enhanceDrawer,80)}})}
function guardNav(){clearInterval(navGuard);let n=0;navGuard=setInterval(()=>{forceNav();if(++n>24)clearInterval(navGuard)},100)}

function addToolCard(){const d=q('#canvasQuickDrawer.open');if(!d||wantedMode!=='elements')return;let box=q('.v140InsertTools',d);qa('.v138ElementTools,.v139InsertTools',d).forEach(x=>x.remove());if(box)return;box=document.createElement('section');box.className='v140InsertTools';box.innerHTML=`<div class="v140ToolHead"><b>Diagramme & Deko</b><span>direkt einfügen</span></div><div class="v140ToolGrid"><button data-v140-tool="chart">${icon('M4 20V4M4 20h16M8 17v-5m5 5V8m5 9V5')}<span>Diagramm</span></button><button data-v140-tool="timeline">${icon('M4 12h16M6 9v6m6-6v6m6-6v6')}<span>Timeline</span></button><button data-v140-tool="sticker">${icon('M12 3a8 8 0 0 0-8 8v6a4 4 0 0 0 4 4h5l7-7v-3a8 8 0 0 0-8-8Z')}<span>Sticker</span></button></div>`;
box.addEventListener('click',e=>{const b=e.target.closest('[data-v140-tool]');if(!b)return;e.preventDefault();e.stopPropagation();({chart:window.openChartDialog,timeline:window.openTimelineDialog,sticker:window.openStickerLibrary})[b.dataset.v140Tool]?.()});
(q('.v133ElementGroups',d)||q('.v134Palette',d)||d).appendChild(box)}
function addTextTools(){const d=q('#canvasQuickDrawer.open');if(!d||wantedMode!=='text')return;d.classList.add('v140TextDrawer');qa('.v138ElementTools,.v139InsertTools,.v140InsertTools,.v139TextHeaderTools,.v128DesktopParityBar,.v129DesktopTextExtras,.v121DesktopFontActions,.v123DesktopTextActions,.v132DesktopTextExtras',d).forEach(x=>x.remove());if(innerWidth<900||q('.v140TextTools',d))return;const bar=document.createElement('div');bar.className='v140TextTools';bar.innerHTML=`<button data-action="font">${uploadIcon}<span><b>Schrift hinzufügen</b><small>TTF, OTF, WOFF oder WOFF2</small></span></button><button data-action="preset">${icon('M12 5v14M5 12h14')}<span><b>Textformat erstellen</b><small>Aus der aktuellen Auswahl</small></span></button><button data-action="manage">${icon('M4 6h16M7 12h10M9 18h6')}<span><b>Formate verwalten</b><small>Sortieren und löschen</small></span></button>`;bar.onclick=e=>{const a=e.target.closest('button')?.dataset.action;if(a==='font')window.v91PickFont?.();if(a==='preset')window.createCustomStylePreset?.();if(a==='manage')window.openTextFormatManager?.()};d.prepend(bar)}
function enhanceDrawer(){if(!editor())return;rememberMode();const d=q('#canvasQuickDrawer.open');if(wantedMode==='elements'&&d&&!elementMarkup){const copy=d.cloneNode(true);qa('.v138ElementTools,.v139InsertTools,.v140InsertTools',copy).forEach(x=>x.remove());elementMarkup=copy.innerHTML}if(wantedMode==='elements')addToolCard();if(wantedMode==='text')addTextTools()}
function directDrawer(mode){const d=q('#canvasQuickDrawer');if(!d)return false;let html='';if(mode==='text'){try{html=mobileTextLibraryHTML()}catch(_){html='<div class="mobileDrawerSection mobileTextLibrary"><div class="mobileLibraryHead"><div><span class="mobileDrawerKicker">TEXT</span><b>Textformate</b></div><button onclick="openTextFormatManager()">Verwalten</button></div><div class="mobileDrawerActions"><button onclick="createCustomStylePreset()">＋ Neues Textformat</button></div></div>'}}else if(mode==='elements'&&elementMarkup)html=elementMarkup;else return false;try{openEditorGroup=mode==='text'?'textLibrary':'elements'}catch(_){}window.v139ForceNav?.(mode);d.dataset.v134Mode=mode;d.dataset.v137Mode=mode;d.classList.add('open');document.body.classList.add('editorDrawerOpen');d.innerHTML=html;qa('.canvasQuickNav button').forEach(x=>x.classList.toggle('active',(x.dataset.v139||x.dataset.v138)===mode));setTimeout(enhanceDrawer,0);return true}

/* The original AI ticket outline is rebuilt from dimensions, so corners and stroke never stretch. */
function frameSvg(w,h,color,width){w=Math.max(90,Math.round(w));h=Math.max(55,Math.round(h));width=Math.max(1,Math.min(30,+width||5));const m=width/2+2,r=Math.max(14,Math.min(48,h*.18,w*.08)),k=r*.55;const d=`M${w-m} ${m+r}V${h-m-r}C${w-m-k} ${h-m-r} ${w-m-r} ${h-m-k} ${w-m-r} ${h-m}H${m+r}C${m+r} ${h-m-k} ${m+k} ${h-m-r} ${m} ${h-m-r}V${m+r}C${m+k} ${m+r} ${m+r} ${m+k} ${m+r} ${m}H${w-m-r}C${w-m-r} ${m+k} ${w-m-k} ${m+r} ${w-m} ${m+r}Z`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><path d="${d}" fill="none" stroke="${esc(color)}" stroke-width="${width}" stroke-linejoin="round"/></svg>`}
function svgData(svg){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
window.v140AddFrame=function(){const o={id:id(),z:nextCanvasZ(),kind:'image',src:'',name:'Ticket-Rahmen',x:130,y:160,w:460,h:170,rotation:0,locked:false,stickerAsset:true,frameAsset:true,style:{borderColor:'#4f4642',borderWidth:5}};o.src=svgData(frameSvg(o.w,o.h,o.style.borderColor,o.style.borderWidth));canvasState.objects.push(o);closeModal?.();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];renderCanvasObjects();renderCanvasInspector();markCanvasDirty();pushHistory();window.v132SyncHits?.();cuteToast?.('Rahmen eingefügt ♡')};
function refreshFrames(){for(const o of canvasState.objects||[]){if(!o.frameAsset)continue;o.style||={};const sig=[Math.round(o.w),Math.round(o.h),o.style.borderColor||'#4f4642',o.style.borderWidth||5].join(':');if(o.frameSignature===sig)continue;o.frameSignature=sig;o.src=svgData(frameSvg(o.w,o.h,o.style.borderColor||'#4f4642',o.style.borderWidth||5));const img=q(`.cobj[data-id="${CSS.escape(o.id)}"] img`);if(img)img.src=o.src}}
window.v140UploadSticker=function(){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif,image/svg+xml,.png,.jpg,.jpeg,.webp,.gif,.svg';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const ratio=Math.max(.2,Math.min(5,img.naturalWidth/Math.max(1,img.naturalHeight))),w=ratio>1.5?320:ratio<.72?150:230,h=Math.round(w/ratio),o={id:id(),z:nextCanvasZ(),kind:'image',src:String(reader.result),name:f.name,x:150,y:150,w,h,rotation:0,locked:false,stickerAsset:true};canvasState.objects.push(o);closeModal?.();canvasState.selectedType='object';canvasState.selectedId=o.id;canvasState.selectedIds=[o.id];canvasState.selectedVectorIds=[];renderCanvasObjects();renderCanvasInspector();markCanvasDirty();pushHistory();window.v132SyncHits?.();cuteToast?.('Sticker-Datei eingefügt ♡')};img.onerror=()=>cuteToast?.('Diese Bilddatei konnte nicht geladen werden');img.src=String(reader.result)};reader.readAsDataURL(f)};input.click()};

const originalSticker=window.openStickerLibrary;
window.openStickerLibrary=function(){originalSticker?.();const modal=q('#modalWrap .v135Modal');if(!modal)return;let tools=q('.v140StickerImport',modal);if(!tools){tools=document.createElement('div');tools.className='v140StickerImport';tools.innerHTML=`<button onclick="v140UploadSticker()">${uploadIcon}<span><b>Eigene Stickerdatei</b><small>PNG, JPG, WebP, GIF oder SVG</small></span></button><button onclick="v140AddFrame()">${frameIcon}<span><b>Ticket-Rahmen</b><small>Aus deiner Illustrator-Datei · frei skalierbar</small></span></button>`;q('.v135StickerGrid',modal)?.before(tools)}};

/* Replace Firebase with a small, inspectable Apps Script/Google Drive sync. */
const syncUrlKey='studia-gas-url',syncSecretKey='studia-gas-key';
function syncState(s,bad=false){const el=q('#v140SyncState');if(el){el.textContent=s;el.classList.toggle('error',bad)}}
function syncConfig(){const url=String(q('#v140SyncUrl')?.value||'').trim(),key=String(q('#v140SyncKey')?.value||'').trim();if(!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/.test(url))throw new Error('Bitte die bereitgestellte Web-App-URL mit /exec einfügen.');if(key.length<12)throw new Error('Der Sync-Schlüssel braucht mindestens 12 Zeichen.');localStorage.setItem(syncUrlKey,url);localStorage.setItem(syncSecretKey,key);return{url,key}}
window.openAccountDialog=function(){const url=localStorage.getItem(syncUrlKey)||'',key=localStorage.getItem(syncSecretKey)||'';openModal(`<div class="v135Modal v140SyncModal"><div class="v135ModalHead"><div><span class="eyebrow">GERÄTE-SYNC</span><h2>Google Apps Script</h2></div><button onclick="closeModal()">×</button></div><p>Synchronisiere Studia über eine private JSON-Datei in deinem eigenen Google Drive.</p><div class="v135FormGrid"><label class="full">Apps-Script-Web-App-URL<input id="v140SyncUrl" type="url" placeholder="https://script.google.com/macros/s/…/exec" value="${esc(url)}"></label><label class="full">Persönlicher Sync-Schlüssel<input id="v140SyncKey" autocomplete="off" placeholder="mindestens 12 Zeichen" value="${esc(key)}"></label></div><div id="v140SyncState" class="v140SyncState"></div><div class="v135ActionRow"><button onclick="v140SyncDownload()">Cloud laden</button><button class="primary" onclick="v140SyncUpload()">Jetzt synchronisieren</button></div><details class="v140SyncHelp"><summary>Einmalige Einrichtung anzeigen</summary><ol><li>Auf script.google.com ein neues Projekt öffnen.</li><li>Den Inhalt aus <b>google-apps-script/Code.gs</b> in den Editor kopieren.</li><li>Bereitstellen → Neue Bereitstellung → Web-App.</li><li>Ausführen als „Ich“, Zugriff „Jeder“, dann bereitstellen.</li><li>Die /exec-URL und denselben geheimen Schlüssel auf Handy und Laptop eintragen.</li></ol><p>Erst auf dem Gerät mit den aktuellen Daten „Jetzt synchronisieren“, danach auf dem anderen „Cloud laden“.</p></details></div>`)};
window.v140SyncUpload=async function(){try{const c=syncConfig();syncState('Daten werden hochgeladen …');const form=new FormData();form.set('action','save');form.set('key',c.key);form.set('payload',JSON.stringify(data));await fetch(c.url,{method:'POST',mode:'no-cors',body:form});syncState('Synchronisierung gesendet ✓');cuteToast?.('Studia wurde synchronisiert ♡')}catch(err){syncState(String(err.message||err),true)}};
window.v140SyncDownload=function(){try{const c=syncConfig(),cb='studiaSync_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script');syncState('Cloud-Daten werden geladen …');const done=()=>{delete window[cb];script.remove()};window[cb]=result=>{try{if(!result?.ok)throw new Error(result?.error||'Cloud-Daten konnten nicht geladen werden.');const remote=JSON.parse(result.payload||'{}');Object.keys(data).forEach(k=>delete data[k]);Object.assign(data,remote);save();syncState('Cloud-Daten geladen ✓');cuteToast?.('Cloud-Daten geladen ♡');setTimeout(()=>location.reload(),500)}catch(err){syncState(String(err.message||err),true)}finally{done()}};script.onerror=()=>{syncState('Web-App nicht erreichbar. Prüfe URL und Bereitstellung.',true);done()};const u=new URL(c.url);u.searchParams.set('action','load');u.searchParams.set('key',c.key);u.searchParams.set('callback',cb);script.src=u.toString();document.head.appendChild(script)}catch(err){syncState(String(err.message||err),true)}};
window.v135CloudAuth=()=>window.openAccountDialog();window.v135CloudUpload=silent=>silent?Promise.resolve():window.v140SyncUpload();window.v135CloudDownload=()=>window.v140SyncDownload();

const baseRender=window.renderCanvasObjects;window.renderCanvasObjects=function(){const r=baseRender.apply(this,arguments);refreshFrames();return r};try{renderCanvasObjects=window.renderCanvasObjects}catch(_){}
const baseInspector=window.renderCanvasInspector;window.renderCanvasInspector=function(){const r=baseInspector.apply(this,arguments);refreshFrames();return r};try{renderCanvasInspector=window.renderCanvasInspector}catch(_){}

/* A genuine paper click clears selection; empty drags remain marquee selection. */
document.addEventListener('click',e=>{if(!editor()||document.body.classList.contains('v137ViewMode'))return;const t=e.target instanceof Element?e.target:null;if(!t||t.closest('.cobj,.vectorObj,.v132Hit,.v138TransformHandle,.pathNode,button,input,select,textarea,[contenteditable="true"]')||!t.closest('#canvasPage,#canvasStage,#canvasObjects,#v132InteractionLayer'))return;canvasState.multiMode=false;clearCanvasSelection?.();window.v132SyncHits?.();renderCanvasInspector?.()},true);

const bodyWatch=new MutationObserver(()=>{if(editor()){guardNav();setTimeout(enhanceDrawer,0)}});bodyWatch.observe(document.body,{attributes:true,attributeFilter:['class']});
const navWatch=new MutationObserver(()=>{if(editor()){rememberMode();forceNav()}});
setTimeout(()=>{const nav=q('.canvasQuickNav');if(nav)navWatch.observe(nav,{childList:true,subtree:true});if(editor()){guardNav();enhanceDrawer()}},250);
document.addEventListener('click',e=>{const b=e.target.closest('.canvasQuickNav button');if(!b)return;const mode=b.dataset.v139||b.dataset.v138||b.dataset.v133;if(!mode)return;e.preventDefault();e.stopImmediatePropagation();wantedMode=mode;setTimeout(()=>{forceNav();if(directDrawer(mode))return;const current=q(`.canvasQuickNav button[data-v139="${mode}"]`)||q(`.canvasQuickNav button[data-v138="${mode}"]`);window.v138NavOpen?.(mode,current);setTimeout(enhanceDrawer,20)},0)},true);
window.addEventListener('resize',()=>setTimeout(()=>{forceNav();enhanceDrawer()},120));
})();
